/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    DeleteButton: typeof import('./src/components/buttons/DeleteButton.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    HomeButton: typeof import('./src/components/buttons/HomeButton.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    NumButton: typeof import('./src/components/buttons/NumButton.vue')['default']
    Numpad: typeof import('./src/components/Numpad.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Status: typeof import('./src/components/Status.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Toast: typeof import('primevue/toast')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
