/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/buttons/BackButton.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DeleteButton: typeof import('./src/components/buttons/DeleteButton.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Listbox: typeof import('primevue/listbox')['default']
    NumButton: typeof import('./src/components/buttons/NumButton.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Status: typeof import('./src/components/top/Status.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    VideoPlayer: typeof import('./src/components/bottom/VideoPlayer.vue')['default']
  }
}
